from abc import ABC, abstractmethod
from uuid import UUID
from app.domain.user import User
from app.domain.generation import Generation

class UserRepository(ABC):
    @abstractmethod
    async def get(self, user_id: UUID) -> User | None: ...
    @abstractmethod
    async def get_by_external_id(self, external_user_id: str) -> User | None: ...
    @abstractmethod
    async def get_by_api_key_hash(self, api_key_hash: str) -> User | None: ...
    @abstractmethod
    async def add(self, user: User) -> None: ...
    @abstractmethod
    async def save(self, user: User) -> None: ...

class GenerationRepository(ABC):
    @abstractmethod
    async def get(self, generation_id: UUID) -> Generation | None: ...
    @abstractmethod
    async def get_by_provider_request_id(self, provider_request_id: str) -> Generation | None: ...
    @abstractmethod
    async def add(self, gen: Generation) -> None: ...
    @abstractmethod
    async def save(self, gen: Generation) -> None: ...
