class AppError(Exception): ...
class Unauthorized(AppError): ...
class RateLimited(AppError): ...
class Banned(AppError): ...
class NotFound(AppError): ...
class Validation(AppError): ...
class InsufficientFunds(AppError): ...
